/**
 * One-time script: deploys CrossChainRepoEscrow to a single chain and registers
 * the 3 relayer addresses (2-of-3 quorum) generated by generateRelayerWallets.js.
 *
 * Run once per chain, then store the printed address in .env as
 * ESCROW_SEPOLIA_ADDRESS / ESCROW_AMOY_ADDRESS / ESCROW_FUJI_ADDRESS.
 *
 * Usage:
 *   RELAYER1_ADDRESS=0x... RELAYER2_ADDRESS=0x... RELAYER3_ADDRESS=0x... \
 *     npx hardhat run scripts/deployCrossChainRepoEscrow.js --network sepolia
 *   (repeat --network amoy, --network fuji)
 */

const { ethers } = require("hardhat");

const THRESHOLD = process.env.RELAYER_THRESHOLD ? parseInt(process.env.RELAYER_THRESHOLD, 10) : 2;

async function main() {
  const relayers = [
    process.env.RELAYER1_ADDRESS,
    process.env.RELAYER2_ADDRESS,
    process.env.RELAYER3_ADDRESS,
  ];

  for (const addr of relayers) {
    if (!addr || !ethers.isAddress(addr)) {
      throw new Error("RELAYER1_ADDRESS, RELAYER2_ADDRESS, RELAYER3_ADDRESS must all be set to valid addresses. Run scripts/generateRelayerWallets.js first.");
    }
  }

  const [deployer] = await ethers.getSigners();
  console.log("Deploying from:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)));
  console.log("Relayers:", relayers);
  console.log("Threshold:", THRESHOLD);

  const CrossChainRepoEscrow = await ethers.getContractFactory("CrossChainRepoEscrow");
  const escrow = await CrossChainRepoEscrow.deploy(relayers, THRESHOLD);
  await escrow.waitForDeployment();

  const address = await escrow.getAddress();
  const chainId = (await ethers.provider.getNetwork()).chainId;

  console.log("\n=== Deployment complete ===");
  console.log("Chain ID:         ", chainId.toString());
  console.log("Escrow address:   ", address);
  console.log("\nAdd to your .env file, e.g.:");
  console.log(`ESCROW_${networkLabel(chainId)}_ADDRESS=${address}`);
}

function networkLabel(chainId) {
  switch (chainId.toString()) {
    case "11155111": return "SEPOLIA";
    case "80002": return "AMOY";
    case "43113": return "FUJI";
    default: return "CHAIN_" + chainId.toString();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
