/**
 * One-time script: deploys CrossChainRepoEscrow (implementation + UUPS proxy) to a
 * single chain and registers the 3 relayer addresses (2-of-3 quorum) generated by
 * generateRelayerWallets.js.
 *
 * CrossChainRepoEscrow is a long-lived singleton — one proxy per chain, never
 * redeployed per trade — so this script deploys both the implementation and its
 * one proxy in a single step via upgrades.deployProxy(), rather than the
 * implementation-only flow used by scripts/deployImplementation.js for the
 * per-project/per-trade contracts.
 *
 * Run once per chain, then store the printed proxy address in .env as
 * ESCROW_SEPOLIA_ADDRESS / ESCROW_AMOY_ADDRESS / ESCROW_FUJI_ADDRESS — the same
 * env vars already used before this contract became upgradeable, now holding the
 * proxy address instead of a plain contract address. No controller changes are
 * needed since that's the only address they ever read.
 *
 * Usage:
 *   RELAYER1_ADDRESS=0x... RELAYER2_ADDRESS=0x... RELAYER3_ADDRESS=0x... \
 *     npx hardhat run scripts/deployCrossChainRepoEscrow.js --network sepolia
 *   (repeat --network amoy, --network fuji)
 */

const { ethers, upgrades } = require("hardhat");

const THRESHOLD = process.env.RELAYER_THRESHOLD ? parseInt(process.env.RELAYER_THRESHOLD, 10) : 2;

async function main() {
  const relayers = [
    process.env.RELAYER1_ADDRESS,
    process.env.RELAYER2_ADDRESS,
    process.env.RELAYER3_ADDRESS,
  ];

  for (const addr of relayers) {
    if (!addr || !ethers.isAddress(addr)) {
      throw new Error("RELAYER1_ADDRESS, RELAYER2_ADDRESS, RELAYER3_ADDRESS must all be set to valid addresses. Run scripts/generateRelayerWallets.js first.");
    }
  }

  const [deployer] = await ethers.getSigners();
  console.log("Deploying from:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)));
  console.log("Relayers:", relayers);
  console.log("Threshold:", THRESHOLD);

  const CrossChainRepoEscrow = await ethers.getContractFactory("CrossChainRepoEscrow");
  const escrow = await upgrades.deployProxy(CrossChainRepoEscrow, [relayers, THRESHOLD], { kind: "uups" });
  await escrow.waitForDeployment();

  const address = await escrow.getAddress();
  const implAddress = await upgrades.erc1967.getImplementationAddress(address);
  const chainId = (await ethers.provider.getNetwork()).chainId;

  console.log("\n=== Deployment complete ===");
  console.log("Chain ID:              ", chainId.toString());
  console.log("Escrow proxy address:  ", address);
  console.log("Implementation address:", implAddress);
  console.log("\nAdd to your .env file, e.g.:");
  console.log(`ESCROW_${networkLabel(chainId)}_ADDRESS=${address}`);
}

function networkLabel(chainId) {
  switch (chainId.toString()) {
    case "11155111": return "SEPOLIA";
    case "80002": return "AMOY";
    case "43113": return "FUJI";
    default: return "CHAIN_" + chainId.toString();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
